services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: "no"
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data
    networks:
      - webui-litellm-net

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    restart: "no"
    command: ["--config", "/app/config.yaml"]
    env_file:
      - litellm/.env
    volumes:
      - ./litellm/config.yaml:/app/config.yaml
    networks:
      - webui-litellm-net

networks:
  webui-litellm-net:
    name: webui-litellm-net

volumes:
  open-webui:
    external: true
